apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::799877389536:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1FASM54DF43SI
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-10T11:57:22Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-04-10T11:57:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1510"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: cc568da5-2fb7-43a8-8cb8-b9e7af998d1a
