apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::799877389536:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1T0RJYFA3JG8S
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-06T12:12:28Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-04-06T12:12:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1388"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2130eff4-cf5a-4b15-b27c-3dae5b804cab
